sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - oracle-java8-installer
      - lib32stdc++6
      - lib32z1
env:
  - NODE_VERSION=6.1.0
#  matrix:
#    - CXX=g++-4.8
install:
  - nvm install $NODE_VERSION
  - npm install -g cordova ionic
before_script:
  - cd OpenBioMapsApp
script:
  - nvm use $NODE_VERSION
  - npm install
  - npm run ionic:build
  - ionic state reset
  - ionic build android
after_script:
  - ls -al platforms/android/build/outputs/apk/
